### ISSUE TITLE
After restarting click bot, it won't spam clicks

### ISSUE THREAD

**Issue by eric15342335** [eric15342335/spam-bot#3]
![Screenshot 2021-01-04 225050](https://user-images.githubusercontent.com/70310617/103547429-596e3380-4edf-11eb-98f8-c661495736ef.png)
Close the spam bot and restart it again can fix this problem.

**Comment by Bluechan0415** [comment]
bruh

**Comment by eric15342335** [comment]
Solved this issue by removing the restart clicks --- just return to menu
