### ISSUE TITLE
Changing spam interval

### ISSUE THREAD

**Issue by Bluechan0415** [eric15342335/spam-bot#6]
e.g. 1 second

**Comment by eric15342335** [comment]
It is possible to do this. But I need to ask you a question,
Is your computer lagging?

**Comment by Bluechan0415** [comment]
on web no
on phone yes

**Comment by Bluechan0415** [comment]
also
why are you gae

**Comment by Bluechan0415** [comment]
also remember to do your hw

**Comment by Bluechan0415** [comment]
ping

**Comment by Bluechan0415** [comment]
ping

**Comment by eric15342335** [comment]
> on web no
> on phone yes
I guess since whatsapp web needs your phone be switched on,
so spamming on web may have a chance to lag your whatsapp app.

**Comment by eric15342335** [comment]
updated

**Comment by eric15342335** [comment]
# How to enable spam interval (0.1 second)
## spam bot
The program will ask you
## spam bot GUI
click "file", then click "enable spam interval" (for *v2-beta-2*)

**Comment by eric15342335** [comment]
Bug detected --- issue [here](https://github.com/eric15342335/spam-bot/issues/12)
Please comment on that issue.
